language: javascript
addons:
  apt:
    packages:
      - openjdk-8-jre  # install Java8 as required by vnu.jar
install:
 - pip install html5validator
script: html5validator --root public/ --also-check-css
