language: python
python:
 - "3.6"
os: linux
addons:
  apt:
    packages:
      - openjdk-8-jre  # install Java8 as required by vnu.jar
install:
 - sudo snap install hugo --channel=extended
 - pip install html5validator
script:
 - hugo
 - html5validator --root public/ --ignore itemprop --also-check-css
notifications:
  email: false
