title = "Wikiotics"
languageCode = "en"
baseURL = "/"
cleanDestinationDir = true
disablePathToLower = true

[taxonomies]
#category = "categories"
tag = "tags"

# While migrating from the old Ductus site, pandoc sometimes returned
# HTML tables rather than markdown ones, so we enable HTML in Markdown.
[markup.goldmark.renderer]
unsafe = true
